name: Build packages

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build_packages:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    concurrency: b2k-${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - linux-x64
          - linux-arm64
          - linux-arm
          - windows-x64
          - windows-arm64
          - osx-x64
          - osx-arm64
      fail-fast: false # windows not working
    steps:
      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: setup NuGet
        uses: nuget/setup-nuget@v2

      - name: checkout source code
        uses: actions/checkout@v4

      - name: dotnet restore
        run: |
          nuget restore src\client.sln -Verbosity Normal -NonInteractive -ConfigFile src/nuget.config

      - name: dotnet publish src/dsc/dsc.csproj
        run: |
          dotnet publish src/dsc/dsc.csproj -r ${{ matrix.platform }} -c Release --no-restore --self-contained true --verbosity detailed

      - name: dotnet publish src\EndpointManagerLauncher\endpointmanagerlauncher.csproj
        if: ${{ matrix.platform == 'win-x64' || matrix.platform == 'win-arm64'}}
        run: dotnet publish src\EndpointManagerLauncher\endpointmanagerlauncher.csproj -r ${{ matrix.platform }} -c Release --no-restore

      - name: Run unit test cases
        run: | 
          dotnet restore src/unittest.sln
          dotnet test src/unittest.sln -c Release --no-restore --verbosity normal
