name: 'CI'

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build-and-release:
    uses: ./.github/workflows/build-and-release.yml
    secrets: inherit
  
  package-docker:
    uses: ./.github/workflows/package-docker.yml
    secrets: inherit

  create-tag:
    if: ${{ github.ref_name == github.event.repository.default_branch }}
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    needs:
      - build-and-release
      - package-docker
    permissions:
      contents: write # needed to mint tag
      actions: write # needed to tigger workflow
    env:
      SHA: ${{ github.sha }}
      TAG_MAJOR: '2'
      TAG_MINOR: '0'
    steps:
      - id: create_id
        run: |
          export TAG_PATCH_BUILD=$(TZ="UTC" date +"%Y%m%d.%H%M")
          echo "TAG=${TAG_MAJOR}.${TAG_MINOR}.${TAG_PATCH_BUILD}" >> ${GITHUB_OUTPUT}

      - name: create tag ${{ steps.create_id.outputs.TAG }} from sha ${{ env.SHA }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.create_id.outputs.TAG }}",
              sha: "${{ env.SHA }}"
            })

      - name: trigger workflow for tag ${{ steps.create_id.outputs.TAG }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ci.yml',
              ref: "refs/tags/${{ steps.create_id.outputs.TAG }}",
            })
